DROP TABLE IF EXISTS Cars;
DROP TABLE IF EXISTS Drivers;

CREATE TABLE Car (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  car_Type VARCHAR(250) NOT NULL,
  is_New NUMBER(1) NOT NULL,
  driver_Id INT
);

CREATE TABLE Driver (

    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    type CHAR(1) NOT NULL,
    car_Id INT
);
