DROP TABLE IF EXISTS Cars;
DROP TABLE IF EXISTS Drivers;

CREATE TABLE Car (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  carType VARCHAR(250) NOT NULL,
  isNew NUMBER(1) NOT NULL,
  driverId INT
);

CREATE TABLE Driver (

    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    type CHAR(1) NOT NULL,
    carId INT
);
